version: '3.8'

services:
  master:
    image: citusdata/citus:11.2
    container_name: master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    depends_on:
      - worker1
      - worker2

  worker1:
    image: citusdata/citus:11.2
    container_name: worker1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  worker2:
    image: citusdata/citus:11.2
    container_name: worker2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mongo1:
    image: mongo:6
    container_name: mongo1
    command: --replSet rs0
    ports:
      - "27017:27017"

  mongo2:
    image: mongo:6
    container_name: mongo2
    command: --replSet rs0
    ports:
      - "27018:27017"

  mongo3:
    image: mongo:6
    container_name: mongo3
    command: --replSet rs0
    ports:
      - "27019:27017"

  redis:
    image: redis:7
    container_name: campus_redis
    ports:
      - "6379:6379"

  fdw_postgres:
    image: postgres:15
    container_name: fdw_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fdw_library
    ports:
      - "5442:5432"
    volumes:
      - fdw_pg_data:/var/lib/postgresql/data

  app:
    image: python:3.13
    container_name: python_client
    working_dir: /app
    volumes:
      - .:/app
    command: tail -f /dev/null
    depends_on:
      - master
      - mongo1

volumes:
  postgres_data:
  redis_data:
  fdw_pg_data:

version: '3.8'

services:
  master:
    image: citusdata/citus:11.2
    container_name: master
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    networks:
      - citus-network

  worker1:
    image: citusdata/citus:11.2
    container_name: worker1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    networks:
      - citus-network

  worker2:
    image: citusdata/citus:11.2
    container_name: worker2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    networks:
      - citus-network

networks:
  citus-network:
    driver: bridge

